### ISSUE TITLE
i assume we didn't setup a twitter auth, but we have that link at server homepage

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#48]
http://localhost:3000/auth/twitter

`status: 404
Error: Cannot GET /auth/twitter
    at raiseUrlNotFoundError (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/express/lib/router/index.js:317:13)
    at /home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/express/lib/router/index.js:335:12)
    at next (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:182:13)
    at SendStream.error (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/send/index.js:421:12)
    at next (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/send/index.js:736:16)
    at onstat (/home/art/Documents/C/r/loopback-tutor-intern-8/node_modules/send/index.js:725:14)
    at FSReqWrap.oncomplete (fs.js:149:21)`

2 options: remove it from homepage or add a provider for twitter too

**Comment by atherdon** [comment]
don't worry about twitter login. i;m trying a different approach with
social logins. just find that link and was curious if i miss something


On 21-May-2018 at 01:22 PM, chauhannishith wrote:


2 options: remove it from homepage or add a provider for twitter too

you had told me that you too were working on passport so i thought that you
might me handling it, no problem will do it in few days

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-8/issues/48#issuecomment-390652178>,
or mute the thread

**Comment by chauhannishith** [comment]
this is also done now, so if you have checked then i can close this

**Comment by atherdon** [comment]
twitter auth works well
